FROM node:17.7.1-alpine3.15 as build
WORKDIR /app

COPY package*.json /app/
RUN npm install

COPY . /app
RUN npm run build


FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
